name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macOS-latest
    env:
      PROJECT: SafeDictionary.xcodeproj
      SCHEME: SafeDictionary-Package
    steps:
    - uses: actions/checkout@v1

    - name: List SDKs and Devices
      run: xcodebuild -showsdks; instruments -s

    - name: Generate Xcode Project
      run: swift package generate-xcodeproj

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        SDK: iphonesimulator
        DESTINATION: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest
